---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: conf.yml

- include: haproxy.yml
  when: haproxy_script_location != ""

- include: filestore.yml
  when: "'file:///' in {{ artifact_store }}"

  when: artifact_store | match
- name: Start Marathon service
  service: name=marathon state=restarted
